# Generated by Django 5.2.1 on 2025-05-21 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_servicecategory_remove_servicesdetail_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Industries',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='category',
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
        migrations.DeleteModel(
            name='ServiceDetail',
        ),
    ]
