# Generated by Django 5.1.3 on 2025-05-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_contactenquiry_delete_industries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactenquiry',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
