# Generated by Django 5.1.3 on 2025-05-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_careerenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactenquiry',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
