# Generated by Django 5.1.3 on 2025-05-24 06:00

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_contactenquiry_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerenquiry',
            name='message',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactenquiry',
            name='message',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactenquiry',
            name='subject',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
    ]
