# Generated by Django 5.1.3 on 2025-05-24 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_rename_message_careerenquiry_message_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careerenquiry',
            old_name='message_name',
            new_name='message',
        ),
    ]
