# Generated by Django 5.0.2 on 2025-05-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_rename_message_name_careerenquiry_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerenquiry',
            name='alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
