# Generated by Django 5.1.3 on 2025-05-22 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_blog_industrycategory_servicecategory_servicedetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceDetail',
        ),
    ]
