# Generated by Django 5.1.3 on 2025-05-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_servicedetail_description_servicedetail_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industrydetail',
            old_name='header_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='industrydetail',
            old_name='header_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='industrydetail',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='industrydetail_image'),
        ),
    ]
