# Generated by Django 5.1.3 on 2025-05-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_rename_header_description_industrydetail_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrycategory',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrycategory',
            name='title_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industrycategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industrycategory',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
