# Generated by Django 5.1.3 on 2025-05-23 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_industrycategory_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrydetail',
            name='industry_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='industry_category', to='adminapp.industrycategory'),
            preserve_default=False,
        ),
    ]
