# Generated by Django 5.1.3 on 2025-05-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidetail',
            name='header_image',
            field=models.FileField(blank=True, null=True, upload_to='industrydetail_image'),
        ),
        migrations.AddField(
            model_name='industrydetail',
            name='header_image',
            field=models.FileField(blank=True, null=True, upload_to='industrytitle_image'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='header_image',
            field=models.FileField(blank=True, null=True, upload_to='industrydetail_image'),
        ),
    ]
