# Generated by Django 5.1.3 on 2025-05-24 06:00

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_aidetail_header_image_industrydetail_header_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidetail',
            name='description',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aidetail',
            name='header_description',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industrycategory',
            name='description',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industrycategory',
            name='title_description',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industrydetail',
            name='description',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industryprocess',
            name='description',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicebenefit',
            name='description',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='description',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='header_description',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceoption',
            name='description',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicetechnology',
            name='description',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
    ]
