# Generated by Django 5.1.3 on 2025-05-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_alter_aidetail_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
