# Generated by Django 5.1.3 on 2025-05-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_alter_servicecategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
