# Generated by Django 5.1.3 on 2025-05-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0019_alter_aicategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrycategory',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
