# Generated by Django 5.1.3 on 2025-05-24 10:21

import django.db.models.deletion
import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0020_industrycategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidetail',
            name='contact_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AIBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', django_summernote.fields.SummernoteTextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='aibenefit_image')),
                ('ai_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aibenefit_category', to='adminapp.aicategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', django_summernote.fields.SummernoteTextField()),
                ('ai_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aiprocess_category', to='adminapp.aicategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
