# Generated by Django 5.1.3 on 2025-05-24 10:35

import django.db.models.deletion
import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0021_aidetail_contact_text_aibenefit_aiprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidetail',
            name='about_description',
            field=django_summernote.fields.SummernoteTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aidetail',
            name='about_image',
            field=models.FileField(blank=True, null=True, upload_to='ai_aboutimage'),
        ),
        migrations.AddField(
            model_name='aidetail',
            name='about_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aidetail',
            name='benefit_description',
            field=django_summernote.fields.SummernoteTextField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AIImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='ai_images')),
                ('ai_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aiimages_category', to='adminapp.aicategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
