# Generated by Django 5.1.3 on 2025-05-24 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0022_aidetail_about_description_aidetail_about_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidetail',
            name='ai_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='aidetail_category', to='adminapp.aicategory'),
            preserve_default=False,
        ),
    ]
