# Generated by Django 5.0.2 on 2025-05-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0023_aidetail_ai_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='aibenefit',
            name='alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aidetail',
            name='about_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aidetail',
            name='header_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiimages',
            name='alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrydetail',
            name='alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrydetail',
            name='header_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serviceoption',
            name='alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
