# Generated by Django 5.0.2 on 2025-05-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0024_aibenefit_alt_aidetail_about_alt_aidetail_header_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_category_image'),
        ),
    ]
