# Generated by Django 5.0.2 on 2025-05-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0025_servicecategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrycategory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='industry_category_image'),
        ),
    ]
