# Generated by Django 5.0.2 on 2025-06-06 04:50

import django.db.models.deletion
import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0027_alter_servicecategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', django_summernote.fields.SummernoteTextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='aiservice_image')),
                ('alt', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aiservice_category', to='adminapp.aicategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
