# Generated by Django 5.2.1 on 2025-06-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0029_aidetail_slug_blog_slug_industrydetail_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industrydetail',
            name='slug',
        ),
        migrations.AddField(
            model_name='industrycategory',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
