# Generated by Django 5.2.1 on 2025-06-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0030_remove_industrydetail_slug_industrycategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aidetail',
            name='slug',
        ),
        migrations.AddField(
            model_name='aicategory',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
