# Generated by Django 5.2.1 on 2025-06-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0031_remove_aidetail_slug_aicategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedetail',
            name='slug',
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
