# Generated by Django 5.2.3 on 2025-06-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0036_metaname_metaproperty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industrydetail',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='industrydetail',
            name='meta_title',
        ),
        migrations.AddField(
            model_name='industrycategory',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industrycategory',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
