# Generated by Django 5.2.1 on 2025-06-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0037_remove_industrydetail_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canonical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('view_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='metaname',
            name='view_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metaproperty',
            name='view_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
