# Generated by Django 5.2.1 on 2025-06-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0038_canonical_metaname_view_name_metaproperty_view_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaname',
            name='detail_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metaproperty',
            name='detail_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
