# Generated by Django 5.2.1 on 2025-06-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0039_metaname_detail_name_metaproperty_detail_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='canonical',
            name='detail_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
